# https://api.youneedabudget.com/
# https://api.youneedabudget.com/v1


### user id
# Returns authenticated user information
GET /user

###
# Returns all categories grouped by category group. Amounts (budgeted, activity, balance, etc.) are specific to the current budget month (UTC).
GET /budgets/last-used/categories


### single budget month
# Returns a single budget month
GET /budgets/last-used/months/2023-05-01

###
# Returns all budget months
GET /budgets/last-used/months

